### ISSUE TITLE
1.17.1

### ISSUE THREAD

**Issue by Athamex** [DiffuseHyperion/LavaRising#3]
[20:27:59] [Server thread/INFO]: [LavaRising] Loading LavaRising v2.3.0-rc1-1.13
[20:27:59] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_17_R1.CraftServer] org/apache/commons/io/FileUtils initializing LavaRising v2.3.0-rc1-1.13 (Is it up to date?)
java.lang.NoClassDefFoundError: org/apache/commons/io/FileUtils
	at tk.diffusehyperion.gamemaster.Components.GameWorld.deleteWorld(GameWorld.java:83) ~[GameMaster-1.0.3-rc1-1.13.jar:?]
	at tk.diffusehyperion.gamemaster.Components.GameWorld.deleteWorld(GameWorld.java:91) ~[GameMaster-1.0.3-rc1-1.13.jar:?]
	at tk.diffusehyperion.lavarising.LavaRising.onLoad(LavaRising.java:188) ~[LavaRising-2.3.0-rc1-1.13.jar:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:425) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1233) ~[patched_1.17.1.jar:git-Purpur-1428]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.apache.commons.io.FileUtils
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:153) ~[patched_1.17.1.jar:git-Purpur-1428]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:105) ~[patched_1.17.1.jar:git-Purpur-1428]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 8 more

**Comment by DiffuseHyperion** [comment]
has been fixed in https://github.com/DiffuseHyperion/GameMaster/releases/tag/v1.0.3-rc2-1.13, thank you for reporting :)
